INSERT INTO users(created, email, first_name, last_name, password, username, role_id)
    VALUE (now(), 'Admin@example.com',
           'Admin', 'Adminov',
           '$2a$10$CR7JV7cChaODSvVWvDezYuFTwkMrs/waPzNWiZl7/rOIpXPZpD9nm',
           'admincheto', 2);

INSERT INTO animals(phylum_id, animal_class_id, animal_order,
                    animal_family, genus, specie_name,
                    scientific_name, conservation_id, habitat,
                    diet_id, skin_id,
                    lifespan, description, created,
                    modified, verified, added_by_id)
VALUES (7, 7, 'Artiodactyla', 'Bovidae', 'Capra', 'Alpine Goat', 'Capra aegagrus hircus', 8, 'Domestic, mountains', 1,
        2, 17,
        'With sweet faces and strong bodies, alpine goats are a common sight on farms and ranches throughout the Western world. The origin of these goats is generally accepted to be the mountainous French countryside, although the species has been domesticated for centuries. Regardless of whether you own a true French Alpine or are purchasing from the American Alpine breed, you can count on your goat to be sweet, friendly, and long-lived – all of which are important qualities for a domestic farm animal.',
        now(), null, true, 1),
       (7, 7, 'Carnivora', 'Felidae', 'Panthera', 'Lion',
        'Panthera leo', 5,
        'Savannahs grasslands and scrub bordering deserts', 2, 2, 14,
        'The lion is a species in the family Felidae and a member of the genus Panthera. It has a muscular deep-chested body short rounded head round ears and a hairy tuft at the end of its tail.',
        NOW(), NULL, false, 1),
       (7, 7, 'Rodentia', 'Sciuridae', 'Sciurus', 'Squirrel',
        'Sciurus carolinensis', 6,
        'Deciduous and mixed forests parks and gardens within cities and suburbs.', 3,
        2, 12,
        'The squirrel is a species in the family Sciuridae and a member of the genus Sciurus. It is native to eastern North America where it is the most prodigious and ecologically essential natural forest regenerator.',
        NOW(), NULL, false, 1),
       (7, 7, 'Carnivora', 'Felidae', 'Panthera', 'Tiger',
        'Panthera tigris', 2,
        'Tropical rainforests temperate forests mangrove swamps grasslands and savannas', 2,
        2, 20,
        'The tiger is a species in the family Felidae and a member of the genus Panthera. It is an apex predator primarily preying on ungulates such as deer and bovids.',
        NOW(), NULL, false, 1),
       (7, 7, 'Proboscidea', 'Elephantidae', 'Loxodonta', 'African elephant',
        'L. africana', 3,
        'Savannahs grasslands woodlands wetlands and forests', 3,
        2, 70,
        'The African elephant is a species in the family Elephantidae and a member of the genus Loxodonta. It is the largest living terrestrial animal with bulls reaching up to 4 m tall at the shoulder.',
        NOW(), NULL, false, 1),
       (7, 7, 'Carnivora', 'Phocidae', 'Mirounga', 'Elephant seal',
        'Mirounga angustirostris', 1,
        'Sandy beaches rocky shores and ice floes', 2,
        2, 22,
        'The elephant seal is a species in the family Phocidae and a member of the genus Mirounga. It is distinguished by its size with males being much larger than females and by its proboscis which can be inflated to produce loud vocalizations.',
        NOW(), NULL, false, 1),
       (7, 7, 'Carnivora', 'Ursidae', 'Ursus', 'Polar bear',
        'Ursus maritimus', 4,
        'Arctic sea ice and adjacent coastal areas', 2,
        2, 25,
        'The polar bear is a species in the family Ursidae and a member of the genus Ursus. It is a large bear approximately the same size as the omnivorous Kodiak bear.',
        NOW(), NULL, false, 1);

INSERT INTO animals_locations(animal_id, locations_id)
VALUES (2, 1),
       (3, (SELECT id FROM locations WHERE continent = 'NORTH_AMERICA')),
       (4, (SELECT id FROM locations WHERE continent = 'ASIA')),
       (5, (SELECT id FROM locations WHERE continent = 'AFRICA')),
       (6, (SELECT id FROM locations WHERE continent = 'NORTH_AMERICA')),
       (7, (SELECT id FROM locations WHERE continent = 'NORTH_AMERICA')),
       (1, 3),
       (1, 6);