name: Java CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Build and Test with Maven
        run: mvn -B package --file pom.xml
      - name: Run docker-compose file
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yml"
