package bg.softuni.animalpedia.models.enums;

public enum Status {
    EXTINCT, EXTINCT_IN_THE_WILD, CRITICALLY_ENDANGERED, ENDANGERED, VULNERABLE, NEAR_THREATENED,
    CONSERVATION_DEPENDENT, LEAST_CONCERN, DATA_DEFICIENT, NOT_EVALUATED
}
